import { Button } from '@/components/common/Button'
import { Navbar } from '@/components/common/navbar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cuevanna Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
      <Button url='/home'>
        Cargar mas peliculas
      </Button>
    </>
  )
}
